### ISSUE TITLE
i have 3 app and i want implement microservice with authtentication

### ISSUE THREAD

**Issue by adrianflda** [vuhrmeister/meteor-ddp-auth#1]
please do you have some example for use the package, i have 3 app and i want implement microservice with authtentication. thanks

**Comment by vuhrmeister** [comment]
Good question ^^

Keep in mind that it's not battle tested. I stopped using it (not because it was not working but because I switched to another solution which works just fine for me now). Possible that I use this approach later again.

What you need is to configure a secret which will be used to authenticate the clients at the provider. Just generate some random string which is secure enough and put it into your settings.json under `DDPAuth.secret`:

```
{
  DDPAuth: {
    secret: 'yourSuperSecretKey'
  }
}
``` 

Then all you have to do is to call `DDPAuth.startProvider()` on startup on your server which controls the user base. On all other servers you need to call `DDPAuth.startClient()` and pass the connection of the provider server:

```javascript
const connection = DDP.connect('https://your-provider-server.de')
DDPAuth.startClient(connection)
```

Finally, on the client, you need to call `DDPAuth.registerLoginHandler(connection)` on startup for every service (connection) you have.

I hope I explained it right and that it helps you.

**Comment by adrianflda** [comment]
thanks for your time, and yes I did exactly what you suggest me and it works very well, my problem its when i  connect to another app that no a users server, I need use authentication for retrieve data in publishing for example. thanks again

**Comment by vuhrmeister** [comment]
In methods and publications you can just check for `this.userId` as you would do on the main server as well. If you set up everything right then the package stores the userId on each connection so it should be available there, see https://github.com/vuhrmeister/meteor-ddp-auth/blob/master/src/server/Client.js#L65

I hope I got your question right.

**Comment by adrianflda** [comment]
in UI app on client:
```javascript
import { AccountsClient } from 'meteor/accounts-base'
import { Meteor } from 'meteor/meteor'
import LoginHandler from './LoginHandler'
import Client from './Client'

__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = Meteor.settings.public.remote.login
export let mServiceConn= DDP.connect(__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL);

const DDPAuth = {
  registerLoginHandler (connection) {
    const instance = new LoginHandler(connection)
    instance.start()
  },
  startClient (connection) {
    const instance = new Client(connection)
    instance.start()
  }
}

export {
  DDPAuth
}

if (Meteor.isClient) {
  DDPAuth.registerLoginHandler(mServiceConn)
}

var conn = DDP.connect('http://localhost:3040')
      let loginToken = Accounts._storedLoginToken();
     conn.call("login", {resume:loginToken},
                             function(err,result) {
                               if (!err) {
                                  conn.call('loginTest', function () {
                                    console.log("Logged in! on: http://localhost:3040")
                                  })
                               } else {
                                  console.log(err)
                               }
                             }
                  );
```
it return "you has been loget out by de server try again [403]"

**Comment by vuhrmeister** [comment]
First, I suggest you to put all DDPAuth code into `/packages/ddp-auth` so you don't mess with your app code. Just copy everything from this repo and execute `meteor add vuhrmeister:ddp-auth`.

Second, set the `ACCOUNTS_CONNECTION_URL` only on the server! This is what it would look in my app:
```javascript
__meteor_runtime_config__.ACCOUNTS_CONNECTION_URL = Meteor.settings.public.remote.login
```
Then it's also worth it to reuse the accounts connection instead of just open a new one as you do. Just use the following code (on the client):
```javascript
export let mServiceConn = Accounts.connection
```

Third, you don't need to write those lines at the end of your example. It's enough to call `registerLoginHandler()`. But you don't have to call it with the accounts connection url but only for all your other servers.

```javascript
DDPAuth.registerLoginHandler('http://localhost:3040')
```

**Comment by adrianflda** [comment]
adrian@Notebook:~/loginBackend$ meteor add vuhrmeister:ddp-auth
 => Errors while parsing arguments:           
                                              
While adding package vuhrmeister:ddp-auth:
error: no such package

**Comment by vuhrmeister** [comment]
Ok, probably you need to name the folder `vuhrmeister:ddp-auth` or just remove `vuhrmeister:` in pacakge.json.

**Comment by adrianflda** [comment]
```javascript
Template.test.events({
  'click [name=searchButton]'(event, templateInstance) {
      var conn = DDP.connect('http://localhost:3040')
      let loginToken = Accounts._storedLoginToken();
      conn.call("login", {resume:loginToken},
                             function(err,result) {
                               if (!err) {
                                  conn.call('searchSomeData', function () {
                                      ///
                                  })
                               } else {
                                  console.log(err)
                               }
                             }
                  );
  }
})
```

i need to connect to mybackendApp and do something like insert, delete, and Meteor.userId()=null, each document have an owner and it must is same Meteor.userId() i have 3 app loginApp, UIapp, backendApp, what you suggest me??
thanks a lot

**Comment by vuhrmeister** [comment]
Create a module where you connect to all your apps and export those connections. Then in all places you want to call a method just import that module and reuse the connections you already set up.

```javascript
// services.js

import { Accounts } from 'meteor/accounts-base'

export const login = Accounts.connection
export const backend = DDP.connect('http://localhost:3040')
export const ui = DDP.connect('http://localhost:xxxx')
```

Again, you don't need to call all those lines of code with that token stuff. All you need is to reuse a connection like that:

```javascript
import { backend } from './services' // wherever your module is located
Template.test.events({
  'click [name=searchButton]' (event, templateInstance) {
    backend.call('searchSomeData', function () { /* ... */ })
  }
})
```

**Comment by vuhrmeister** [comment]
Btw: for what do you need the UI app as a backend? For me it looks like you can handle all 3 apps in only one just fine.

If you don't REALLY need to separate your app into microservices, then you're better off by just maintaining one single app.

**Comment by adrianflda** [comment]
thanks again I will try to reproduce your advice in may project.
I need more than 3 app because each one work hurdles with they respective data, calling http api, process information, and de maintenance is very hard in one monolithic app to.
once more thanks, i new in meteor bat i like it

**Comment by adrianflda** [comment]
hello @vuhrmeister  i just did my work, thanks to you, just calling DDPAuth.registerLoginHandler(mServiceConn) before mServiceConn.call(''anyMethod") on mServiceConn app, and wala Meteor.usersId() is same in UI and Backend, now i can doe: 
if (!Meteor.userId()){ return false}
document.owner = Meteor.userId()
insert(document)
thanks again

**Comment by vuhrmeister** [comment]
Great!

**Comment by adrianflda** [comment]
hello @vuhrmeister i did my own version of your code, and i appreciated that you look at it and suggest me some better practices. help me to do better things. thanks
https://github.com/tritrul/ddp-auth-plus
